version: "2.1"
services:
  code-server:
    # image: lscr.io/linuxserver/code-server
    build: .
    container_name: pio-code-server
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Europe/Rome
      - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=test.io #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
      # - /path/to/appdata/config:/config
    ports:
      - 8008:8008
      - 8010:8010
      # - 8080:8080
      - 8443:8443
    restart: unless-stopped